### ISSUE TITLE
Visual Studio 2017 did not sugget me to convert the linq query to a foreach loop

### ISSUE THREAD

**Issue by Anduin2017** [kendrahavens/ProductivityFeatures#2]
Hello.

My environment:

```
Visual Studio 2017 15.8.8
```

Last git commit

```
a3ba23ad
```

### Repro steps

Open the `.sln` file with latest Visual Studio.

Go to the line: 
[Productivity-15.8/ShowMeUpdates.cs Line 147](https://github.com/kendrahavens/Productivity-15.8/blob/master/Productivity-15.8/ShowMeUpdates.cs#L147)

Place you cursor in the linq query of shortGreeting.
Type (Shift + Alt + plus symbol) to select only the linq query.
Type (Ctrl + .).

### Desires behavior

Convert the linq query into a foreach loop.

### Observed behavior

![mistake](https://oss.aiursoft.com/ColossusPublic/abc736d18b084e2da7481a56b6be23ca.png?w=1366&h=768)

Visual Studio suggested to convert my code to:

```csharp
        public void LinqToForEach()
        {
            var greetings = new List<string>() { "hi", "yo", "hello", "howdy" };

            IEnumerable<string> shortGreeting =
                from greet in greetings
                where greet.Length < 3
                select greet;
        }
```

Thank you if you could help me!

**Comment by kendrahavens** [comment]
Hey, sorry I was so late in responding to this issue!

This refactoring is very particular in that you need to **only have the linq query selected**. Here is a gif showing how to trigger the codefix:
![convert-linq-to-foreach](https://user-images.githubusercontent.com/8293542/53141511-44839380-3545-11e9-8cad-13d47c1befdb.gif)

**Comment by Anduin2017** [comment]
Ok. Thank you @kendrahavens ! I have successfully repro that!
