### ISSUE TITLE
.editorconfig warnings/error support

### ISSUE THREAD

**Issue by MarkPflug** [kendrahavens/ProductivityFeatures#5]
Hello,
I asked a question in the .NET community standup this morning about the .editorconfig warnings work that you demoed. My question was whether you had considered how this feature would interact with warnings/errors configured in MSBuild (csproj). I believe the response was that using .editorconfig allowed the configuration to be more easily shared between projects than a csproj implementation, since .editorconfig applies in a "cascading" manner and thus common settings can be applied to multiple projects. That makes total sense, and I completely agree with the design goal. 

Have you considered using [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019) instead? Directory.Build.props would allow the settings to cascade/inherit in the same way that .editorconfig does, and already integrates with MSBuild, so wouldn't require any extra work to integrate.

.editorconfig is a wonderful thing, but it seems that up to this point it is focused on code style, with which warnings/errors don't totally align. This feature will be duplicating functionality that has historically been managed through the MSBuild (csproj). I would expect a command line build to be producing the same warnings/errors as the IDE, so an .editorconfig implementation would require adding some smarts to the existing MSBuild scripts to understand .editorconfig.

It's hard for me to find documentation on some of the MSBuild properties, but some of the ones I can find/remember are:
- **NoWarn** (error list) suppress listed warnings. These warnings will simply not be emitted by the compiler.
- **WarningsAsErrors** (error list) a list of specific warnings to treat as errors.
- **TreatWarningsAsErrors** (true/false) treats all warnings as errors. Defaults to false.
- **WarningsNotAsErrors** (error list) can be used with TreatWarningsAsErrors to not elevate certain warnings to errors. This is a lesser-known property, because the VS properties UI didn't expose it, which is unfortunately because it is very useful.
- **WarningLevel** (0-4) Not really sure how this works, but I think the default is 4 which enables all warnings.

The way I like to setup projects is to turn on TreatWarningsAsErrors, then exclude certain errors `<WarningsNotAsErrors>CS1591,CS0612,CS1030`. Those 3 are a few that I actually care about, but the community could probably provide a more complete set. These will continue to surface as warnings, so won't "break the build".

CS1591 : missing doc comments on public members. I turn this on because too many team members will provide empty comments to suppress the error, which is harder to detect and fix than a warning. There are a lot of related warnings (like [CS1573](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1573)) that might also be reasonable to exclude.

CS0612: warnings about obsolete usage. Debatable if this should be an error, but I find that sometimes I "Obsolete" something, but continue to use it internally. I think CS0618 is similar

CS1030: explicit warning pragmas (#warning). I like to use these as more aggressive "TODO". Elevating them doesn't make sense when #error also exists.

My apologies if this is an inappropriate place to discuss this. Point me the right way if there is somewhere better. Thanks! (side note: the VS test explorer is pretty great now!)

**Comment by kendrahavens** [comment]
I'm following up on this with the team, but before they hop on this issue with replies, I wanted to say feel free to open these issues on https://github.com/dotnet/roslyn/issues. We have a question tag just for such things!

**Comment by MarkPflug** [comment]
No problem, moved to: https://github.com/dotnet/roslyn/issues/38684
Thanks for the response. Closing this issue here.
